services:
  - type: web
    name: linkdev-backend
    env: node
    region: oregon
    buildCommand: npm install && npm run postinstall
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: ALLOWED_IMAGE_TYPES
        value: image/jpeg,image/jpg,image/png,image/gif,image/webp